pipeline:
  name: remoteBitrsie
  identifier: remoteBitrsie
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: bitriseP
        identifier: bitriseP
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Bitrise
                  name: BitSte1
                  identifier: BitSte1
                  spec:
                    uses: https://github.com/bradrydzewski/test-step.git
                    with:
                      Appium_version: "123"
                      Appiumversion: "123"
