pipeline:
  name: remoteT1
  identifier: remoteT1
  projectIdentifier: defaultproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: testRemote
                  identifier: testRemote
                  spec:
                    uses: actions/hello-world-javascript-action@v1.1
