pipeline:
  identifier: Build_VikasTest_1688987724121
  name: Build VikasTest
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: VikasHaritwal93/VikasTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
