pipeline:
  identifier: Build_VikasHaritwal93_VikasTest_1701963204423
  name: Build VikasTest
  orgIdentifier: default
  projectIdentifier: Default_Project_1669200051613
  properties:
    ci:
      codebase:
        connectorRef: account.testGithub
        repoName: VikasTest
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
